music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index]
  

end

music_app/app/models/album.rb
class Album < ApplicationRecord

    validates :title, :year, :band_id, :live, presence: true
    validates :live, inclusion: {in: [true, false]}

    belongs_to :band,
        foreign_key: :band_id,
        class_name: :Band

end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true

    has_many :albums,
        foreign_key: :band_id,
        class_name: :Album

end

music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, :password_digest, :session_token, presence: true
    validates :email, :session_token, uniqueness:true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def self.find_by_credentials(email, password)
        
        user = User.find_by(email: email)
        
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    
    def password
        @password
    end
    
    def password=(password)
        @password = password # why do you need this line
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

    
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
        render :new
    end

    def create
        @album = Album.new(album_params)

        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:errors] = ["Invalid entries"]
            redirect_to new_band_album
        end
    end

    def edit
        @album = Album.find(params[:id])
        render :edit
    end

    def update
        @album =Album.find(params[:id])

        if @album.update(album_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = ["Invalid edits"]
            redirect_to edit_album_url(@album)
        end
    end

    def show
        @album = Album.find(params[:id])
        render :show
    end

    private

    def album_params
        params.require(:album).permit(:title, :year, :band_id, :live)
    end

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?, :logout!, :current_user

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token! # why
        session[:session] = nil
        @current_user = nil
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end
    
    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def require_logged_out
        redirect_to user_url(self) if logged_in?
    end

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def new
        render :new
    end

    def create
        @band = Band.find(band_params)

        if @band.save  
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            redirect_to new_band_url
        end
    end

    def edit
        @band = Band.find(params[:id])
        render :edit
    end

    def update
        @band = Band.find(params[:id])

        if @band.update(band_params)
            redirect_to bands_url
        else
            flash.now[:errors] = @band.errors.full_messages
            redirect_to edit_band_url
        end
    end

    def destroy
        @band = Band.find(params[:id])
        @band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]
    before_action :require_logged_out, only: [:new, :create]

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["Invalid Credentials!"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
        render :show
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ["Invalid username or password"]
        end
    end

    private


    def user_params
        params.require(:user).permit(:email, :password)
    end

end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/new.html.erb
<h3>Let's create a new album, guy</h3>

music_app/app/views/albums/show.html.erb
<h2><%= @album.title %></h2>

<div>no tracks to display yo</div>

<h4>Links</h4>

    <form action="<%= edit_album_url(@album) %>" method="get">
        <input type="submit" value="Edit Album">

    </form>

    <form action="<%= albums_url(@album) %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Destroy Album">
    </form>

        <form action="<%= edit_album_url(@album) %>">
        <input type="submit" value="Edit Album">

    </form>

     </form>

        <form action="<%= band_url(@album.band_id) %>">
        <input type="submit" value="Back to Band">

    </form>
    

music_app/app/views/bands/edit.html.erb
<h1>EDIT <%= @band.name.upcase %></h1>

<table>
    <tr>
        <td>Name</td>
        <td>
            <form action="<%= band_url(@band) %>" method="get">
                <input type="text" name="band[name]" value="<%= @band.name %>">
            </form>
        </td>
    </tr>

</table>

music_app/app/views/bands/index.html.erb
<h1>All Bands</h1>

    <ul>
        <% @bands.each do |band| %>
            <form action="<%= band_url(band) %>" method="get">
                <input type="submit" name="band[name]" value="<%= band.name %>">
            </form>
            
        <% end %>
        
    </ul>

    <h3>Links</h3>
    
    <form action="<%= new_band_url %>" method="post">
        <input type="submit" name="band[name]" value="New band">
    
    </form>

music_app/app/views/bands/new.html.erb
<select name="" id="">
    <option value=""></option>
    <option value=""></option>
    <option value=""></option>
</select>

music_app/app/views/bands/show.html.erb
<h2><%= @band.name %></h2>

    <% @band.albums.each do |album| %>
        <form action="<%= album_url(album) %>" method="get">
            <input type="submit" value="<%= album.title %> Album">
        </form>    
    <% end %>
    

  <h3>Links</h3>

  <form action="<%= new_band_album_url(@band) %>" method="get">
    <input type="submit" value="Add/Create New Album">
  </form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Music App</h1>
    <%= yield %>
    <% if logged_in? %>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout">
        </form>
    <% elsif !logged_in? %>
        <a href="<%= new_user_url %>">Sign-Up</a>
    <% end %>

  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Sign Up Here</h1>

<form action="<%= users_url(@user) %>" method="post">

    <label for="user_email">Email:</label>
    <input type="text" name="user[email]" id="user_email">
    <br>

    <label for="user_password">Password (minimum 6 characters):</label>
    <input type="password" name="user[password]">
    <br>

    <input type="submit" value="Sign Up">

</form>

music_app/app/views/users/show.html.erb
<h1>this is a show page or a user</h1>
<h1><%= @user.email %></h1>